name: imaging_course_minio_day5_2023
channels:
  - bioconda
  - conda-forge
  - defaults
  - ome
dependencies:
  - python == 3.12.*
  - conda-forge::minio-client
  - pip
  - pip:
    - napari[all]
    - napari-ome-zarr==0.5.2

